# Generated by Django 6.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0004_propertyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(
                choices=[
                    ('apartment', 'Apartment'),
                    ('house', 'House'),
                    ('villa', 'Villa'),
                    ('condo', 'Condo'),
                    ('studio', 'Studio'),
                    ('cabin', 'Cabin'),
                ],
                max_length=50,
            ),
        ),
    ]
