# Generated by Django 6.0.6 on 2026-06-21 14:10

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0006_alter_timestamps_to_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
